#!/bin/bash

### BEGIN INIT INFO
# Provides:            zookeeper
# Required-Start:      $local_fs $remote_fs $syslog
# Required-Stop:       $remote_fs $syslog
# Default-Start:       3 5
# Default-Stop:        0 1 2 6
# Short-Description:   Zookeeper daemon
# Description:         Start zookeeper service
### END INIT INFO

ulimit -n 65530
export rc_ulimit="-s 65530"
export JAVA_HOME=/opt/sapjvm_7/jre
export PATH=/usr/bin:/sbin:/bin:/usr/sbin:$JAVA_HOME/bin

[ -f /etc/rc.status ] && . /etc/rc.status

rc_reset

case "$1" in
    start)
    echo -n $"Starting Zookeeper"
    startproc -u zookeeper -g zookeeper -l /app/zookeeper/log/console -s -t 2 /app/zookeeper/conf/start_sf.sh
    rc_status -v
    ;;

    stop)
    echo -n $"Stopping Zookeeper"
    killproc -G /app/zookeeper/conf/start_sf.sh
    rc_status -v
    ;;

    restart)
    $0 stop
    $0 start
    rc_status
    ;;

    status)
    echo -n "Checking for service Zookeeper"
    checkproc /app/zookeeper/conf/start_sf.sh
    rc_status -v
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

rc_exit
