Encoding:
  Enabled: false
TrailingBlankLines:
  Enabled: false
LineLength:
  Max: 120
# disable new "style cop" added in v0.20.1 (~Mar/Apr 2014)
SingleSpaceBeforeFirstArg:
  Enabled: false
AllCops:
  # Exclude certain files...
  Exclude:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'